# wrangler.toml
name = "your-diaper-tracker-worker" # Cloudflare worker name
main = "src/index.js"               # Worker entry point

compatibility_date = "2024-09-23"   # Enable Node.js compatibility features
compatibility_flags = [ "nodejs_compat" ]

# Static asset (public folder) serving configuration
[site]
bucket = "./public"

# Build configuration
[build]
command = "npm install" # Install dependencies

# Environment variables (non-secret)
[vars]
AUTH0_CLIENT_ID = "your_production_auth0_client_id"
AUTH0_ISSUER_BASE_URL = "https://your-auth0-domain.auth0.com"
# For local development, BACKEND_SERVICE_URL can point to a local backend.
# For deployed environments (staging/production), this should be configured as a SECRET
# in the Cloudflare dashboard and NOT hardcoded here.
BACKEND_SERVICE_URL = "http://localhost:3000" # Example for local dev
# Add other necessary non-secret variables here

[env.staging]
name = "your-diaper-tracker-worker"
# Staging environment variables (vars are not inherited, define them explicitly here)
[env.staging.vars]
AUTH0_CLIENT_ID = "your_production_auth0_client_id" # Or a staging specific one if available
AUTH0_ISSUER_BASE_URL = "https://your-auth0-domain.auth0.com" # Or a staging specific one
# For deployed environments (staging/production), BACKEND_SERVICE_URL should be configured as a SECRET
# in the Cloudflare dashboard and NOT hardcoded here.
BACKEND_SERVICE_URL = "https://your-staging-backend-service-url.com" # Example for staging
# Add other necessary non-secret variables here
# route = "staging-your-app.your-domain.com/*" # Optional: if you have a specific route for staging
