# wrangler.toml
name = "your-diaper-tracker-worker" # Cloudflare worker name
main = "src/index.js"               # Worker entry point

compatibility_date = "2024-09-23"   # Enable Node.js compatibility features
compatibility_flags = [ "nodejs_compat" ]

# Static asset (public folder) serving configuration
[site]
bucket = "./public"

# Build configuration
[build]
command = "npm install" # Install dependencies

# Environment variables (non-secret)
[vars]
AUTH0_CLIENT_ID = "your_production_auth0_client_id"
AUTH0_ISSUER_BASE_URL = "https://your-auth0-domain.auth0.com"
# Add other necessary non-secret variables here

[env.staging]
# name = "your-diaper-tracker-worker-staging" # Optional: if you want a different Worker name for staging
# vars = { AUTH0_CLIENT_ID = "your_staging_auth0_client_id", OTHER_VAR = "staging_value" } # Optional: for environment-specific variables
# route = "staging-your-app.your-domain.com/*" # Optional: if you have a specific route for staging
